return {
	"rktjmp/lush.nvim",
	"tjdevries/colorbuddy.nvim",
	{ "Mofiqul/vscode.nvim" },
	{ "sainnhe/gruvbox-material" },
	{ "marko-cerovac/material.nvim" },
	{ "gbprod/nord.nvim" },
	{ "mhartington/oceanic-next" },
	{ "ofirgall/ofirkai.nvim" },
	{ "rmehri01/onenord.nvim" },
	{ "Yazeed1s/minimal.nvim" },
	{ "kdheepak/monochrome.nvim" },
	{ "lourenci/github-colors" },
	{ "Mofiqul/dracula.nvim" },
	{ "ellisonleao/gruvbox.nvim" },
	{ "lalitmee/cobalt2.nvim" },
	{ "metalelf0/jellybeans-nvim" },
}
